version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dynamo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhi
      POSTGRES_DB: dynamo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dynamo_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:abhi@db:5432/dynamo_db
      - GROQ_MODEL=openai/gpt-oss-20b
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=dynamo-dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: dynamo_frontend
    restart: always
    environment:
      - API_HOST=backend
      - API_PORT=8000
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  pgdata: